### ISSUE TITLE
automatically run generated code snippet for testing

### ISSUE THREAD

**Issue by ahmadnassri** [Kong/httpsnippet#10]
###### idea:
- convert and execute `full.json` output for every target in the command line
- response from mockbin will give a HAR object, that can be used to compare against original source (should be 1:1 match, with some additional transport headers)
###### challenges:
- some languages might need compiling
- can all languages can output a clean string to stdout?
- forcing snippets generators to have a `console.log` function for this to work, perhaps in an `option` flag
  - tests can check for existence of said options flag, but not for actual implementation .. that'll be human eye

**Comment by montanaflynn** [comment]
+1! As for the challenges:

> Some langs need compiling

Make to the rescue! My [palindromes repo](https://github.com/montanaflynn/palindromes) has an example of compiling multiple languages (and it's also using [benchmarker](https://github.com/montanaflynn/benchmarker) to run them all from node, it could easily be modified to compare the stdout)

> Can all langs output a string

I don't see why not, this should actually be in the spec, like the output could always be status code followed by the response body for example.

> forcing snippets generators to have a console.log function for this to work, perhaps in an option flag

I don't understand, can you clarify?

**Comment by ahmadnassri** [comment]
> > forcing snippets generators to have a console.log function for this to work, perhaps in an option flag
> 
> I don't understand, can you clarify?

how do I enforce this with tests ... I can't think of anything short of checking them with my human eye ..

**Comment by montanaflynn** [comment]
> how do I enforce this with tests ... I can't think of anything short of checking them with my human eye ..

I think we're on the same page in that the tests would run the generated code which makes a request to mockbin.com/har allowing us to compare the response against a defined set of expected properties. 

I'm still unsure of what you're referring to as "this" and "them" and why a console.log would be needed.

**Comment by ahmadnassri** [comment]
I was thinking of doing the check before running the code ..  hence attempting to _detect_ a `console.log` existence in all languages ...

but of course "running" the code, would also be indicative of that as well ... I just prefer systematic testing rather than 2 in 1 ...
