### ISSUE TITLE
Request language R cran

### ISSUE THREAD

**Issue by laurentdebricon** [Kong/httpsnippet#101]
https://cran.r-project.org/web/packages/RCurl/index.html

**Comment by wilder** [comment]
I would like to work on this! How can I proceed? Is someone already implementing it?

**Comment by darrenjennings** [comment]
@wilder sorry for no communication. @ahmadnassri and myself just recently committed to maintaining httpsnippet again. No one has taken this AFAIK, so feel free to create a PR. Check the wiki https://github.com/Kong/httpsnippet/wiki/Creating-Targets

**Comment by wilder** [comment]
@gabrielakoreeda has made a nice PR about this issue! #131

**Comment by darrenjennings** [comment]
Awesome thanks for the heads up. Hoping to get tests passing in the next week so we can merge PRs like this without headaches soon.

**Comment by darrenjennings** [comment]
Tests are green on master. Waiting on @gabrielakoreeda's PR which is off to a great start.

**Comment by darrenjennings** [comment]
Closed by #131
