### ISSUE TITLE
Double quotes in curl snippets

### ISSUE THREAD

**Issue by demystifier** [Kong/httpsnippet#106]
Currently curl snippets are generated with single quotes. Yes, improved readability as discussed in this [issue](https://github.com/Kong/httpsnippet/pull/29)  however it takes away the ability to have env variables in curl and let shell replace them.  

FR: Anyway you can add a user controlled option to generate curl snippets with double quotes?

UseCase: 
I landed on this page after opening a FR with a platform that uses httpsnippet. For headers like authorization tokens, it is very helpful to set them as env variable in the generated snippets and let the users set those env variables in shell.

**Comment by darrenjennings** [comment]
Closing in favor of #115. Thanks for the note!
