### ISSUE TITLE
HTTP request

### ISSUE THREAD

**Issue by slchorne** [Kong/httpsnippet#107]
Can you also generate code in just raw/native HTTP request format. AKA something like this:

POST /wapi/v2.3/request HTTP/1.1
Host: server.org
Authorization: Basic xyzzy
Content-Type: application/json

{
   "object": "extensibleattributedef",
   "data": {
        "name":"AA-test-01",
        "type":"STRING",
        "comment":"Geoff's test EA"
   }
}

**Comment by darrenjennings** [comment]
This will be fixed by #99

**Comment by darrenjennings** [comment]
Closed by #99
