### ISSUE TITLE
Package 'php5-cli' has no installation candidate

### ISSUE THREAD

**Issue by jonahsnider** [Kong/httpsnippet#146]
```shell
E: Package 'php5-cli' has no installation candidate
```
https://github.com/Kong/httpsnippet/blob/c780dad09b014a1bb28e463b4b058b2d40ae2124/.travis.yml#L10

Looks like all CI tests are broken due to the PHP 5 CLI not being installable anymore.

**Comment by darrenjennings** [comment]
@pizzafox thanks for catching this
