### ISSUE TITLE
PHP Wordpress API

### ISSUE THREAD

**Issue by pimterry** [Kong/httpsnippet#151]
Would you be open to supporting Wordpress's HTTP API? See https://developer.wordpress.org/plugins/http-api/ for the details.

Looks like it shouldn't be too difficult. There's a Paw extension that does this already available at https://github.com/mittsh/Paw-WordPressCodeGenerator/blob/master/php.mustache, which would be a good starting point.

**Comment by darrenjennings** [comment]
@pimterry currently looking at a plugin architecture for httpsnippet so that we don't support "all api clients under the sun" by default, and also to not discriminate. In the meanwhile, will add the label "targets", thanks for the feedback.

**Comment by dimitropoulos** [comment]
I'm going to close this because this isn't something that we're going to be able to implement in the near term since we dont' have anyone that could write it.  If you can add it, I'd be happy to at least review it!  If it can't be in the project by default it can at least be a nice plugin!
