### ISSUE TITLE
Axios conversion

### ISSUE THREAD

**Issue by joshgrib** [Kong/httpsnippet#155]
This issue is to add an [axios ](https://github.com/axios/axios) conversion. I saw [PR 148](https://github.com/Kong/httpsnippet/pull/148) but didn't see why it was closed, or if those changes have just been lost.

I'd be happy to do the implementation and open a PR for it, just wanted to check if there's a reason the other PR was rejected.

Thanks!

**Comment by darrenjennings** [comment]
> Surprised no one has filed a ticket for axios

https://github.com/Kong/httpsnippet/issues/69#issuecomment-471342502 😂 

@joshgrib the author closed that PR mysteriously so all targets are welcome for now. It is possible that we would extract out library implementations from the core into a plugin system in the future, but for now, it is welcome!

**Comment by nixoncode** [comment]
Axios support would be really appreciated by me 😉

**Comment by nixoncode** [comment]
I came here from [Insomnia.rest](https://insomnia.rest/) - I don't use this package directly but its my guess that if its added, Insomnia will pick it up automatically on the next update 

![image](https://user-images.githubusercontent.com/15726312/72666163-a502a580-3a20-11ea-9ebc-e239e3864e01.png)

**Comment by rohit-gohri** [comment]
Opened a PR here: #176 
Please give feedback if the output format can be changed/improved.
