### ISSUE TITLE
Problem with generation

### ISSUE THREAD

**Issue by lfaoro** [Kong/httpsnippet#156]
What is the problem with the definitions?
`$ httpsnippet ./spark_swagger.json -t go`

error:
```
✖ spark_swagger.json failed validation: (undefined: undefined) should have required property 'method'
✖ spark_swagger.json failed validation: (undefined: undefined) should have required property 'url'
✖ spark_swagger.json fail: Cannot read property 'convert' of undefined
```

file: https://doc.fireblaze.io/spark_swagger.json

**Comment by darrenjennings** [comment]
that is a swagger file, while httpsnippet accepts HAR's. See [#usage](https://github.com/Kong/httpsnippet#usage)
