### ISSUE TITLE
Site https://apiembed.com/ is failing

### ISSUE THREAD

**Issue by hchiapella** [Kong/httpsnippet#159]
Hi there!

The site https://api.apiembed.com/ has the iframe broken.

Regards,
Hernán
![APIEMBED](https://user-images.githubusercontent.com/12820059/74754200-07cda380-5250-11ea-9192-821fa8fb812c.png)

**Comment by darrenjennings** [comment]
@hchiapella this should be resolved.

**Comment by hchiapella** [comment]
Great, is working, thanks! :-)
