### ISSUE TITLE
Add Java HttpClient support 

### ISSUE THREAD

**Issue by VoidScute** [Kong/httpsnippet#162]
I come here insomia generate code feature.
Since Java 11 there is a new api, add doc can be found here (for the openjdk)

https://openjdk.java.net/groups/net/httpclient/recipes.html

**Comment by VoidScute** [comment]
@darrenjennings what kind of help do you need ? How can i if i can ?

**Comment by darrenjennings** [comment]
@HumanG33k ideally someone with java background would write the target. If you wanted to take a stab at writing a new target "HttpClient" for Java:

https://github.com/Kong/httpsnippet/wiki/Creating-Targets 
https://github.com/Kong/httpsnippet/tree/master/src/targets/java

**Comment by johanhammar** [comment]
Looks like this was implemented in https://github.com/Kong/httpsnippet/pull/170/

**Comment by reynolek** [comment]
That looks to be correct, my fault for not searching for this issue when I merged that in. This is available in v1.21.0+
