### ISSUE TITLE
Using the 'json()' method in Python code that uses requests.

### ISSUE THREAD

**Issue by demitri** [Kong/httpsnippet#167]
I use a program called [Stoplight Studio](https://github.com/stoplightio/studio) that in turn uses `httpsnippet` to generate sample code. I had a suggestion for the Python+requests code which I filed an issue with here: [#423](https://github.com/stoplightio/studio/issues/423#issuecomment-638121769).

Repeated here:
This is really minor. In the generated docs, under "Try It" -> "Code Generation" -> "Python/Requests", the last line of the code generated is:

```python
print(response.text)
```

The requests package has a `.json()` method, described here. The docs can check if the return data is `application/json`, and if so, suggest this line:

```python
print(response.json())
```

I think the question is whether `httpsnippet` is informed of the API response type.

Thanks!

cc @philsturgeon

**Comment by erunion** [comment]
There's an open PR for this in https://github.com/Kong/httpsnippet/pull/153

**Comment by demitri** [comment]
Ah,  great!

**Comment by reynolek** [comment]
If anyone is interested in fixing up the tests in that PR, i would be happy to merge it.

**Comment by jgiovaresco** [comment]
@reynolek #181 should fix tests ;)
I had to create a new PR and cherry the commit from the original author
