### ISSUE TITLE
Automating release

### ISSUE THREAD

**Issue by jgiovaresco** [Kong/httpsnippet#185]
It would be nice to automate the release. 

I've configured [semantic-release](https://github.com/semantic-release/semantic-release) in several projects and it does a great job. 

To implement this we should start by enforcing a standard for commit messages. semantic-release is able to generate a CHANGELOG automatically. 

I suggest using [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) as standard. I think it quite widely used and semantic-release supports it, therefore it might be a great candidate.

Besides we would be able to enforce conventionalcommits standard with [commitlint](https://github.com/conventional-changelog/commitlint)

**Comment by develohpanda** [comment]
Interesting, we don't necessarily need to enforce conventionalcommits from individual contributors, rather just provide an appropriate commit message while merging a PR using a Squash & Merge strategy: https://www.conventionalcommits.org/en/v1.0.0/#do-all-my-contributors-need-to-use-the-conventional-commits-specification.

Although I can also see the potential drawbacks of this approach (multiple commit types in a PR).

So with what you are proposing, we might have:
- commitlint for all contributors
- rebase & merge strategy (no other is allowed)

Seems alright to me for this project! With a project that has higher contributor traffic I'd be less inclined to enforce conventionalcommits to all contributors (I think 🤔).

> It would be nice to automate the release.

What would a release be triggered by - a merge to master, or something else?

**Comment by jgiovaresco** [comment]
> What would a release be triggered by - a merge to master, or something else?

Exactly, for every merge in master, we would trigger semantic-release. It will then analyze the commits added since the last release to decide if a release needs to be created.
* `fix:` will trigger a patch release, it means that the patch version number will be incremented
* `feat:` will trigger a feature release, it means that the minor version number will be incremented
* all other type (`perf`, `chore`, `release`...) won't trigger any release
* and finally for any commits containing `BREAKING CHANGE` in the message, it will trigger a breaking release, it means that the major version number will be incremented.

**Comment by develohpanda** [comment]
Seems reasonable to me 👍 definitely a step forwards. It would be awesome to also add any documentation or notes to the readme as part of this feature (doesn't have to be extensive).

I set this up (finally) for a personal repo to test it out and am happy with it. 😄

**Comment by philsturgeon** [comment]
Strongly recommend giving this a go for packages that are taking a bit more time managing than you'd like. 

For example I'd be excited to use #132 but it's not been released yet. If release was automated you'd not have to worry about doing it manually. 

Setting it up can be pretty simple, here's how I did it for another tool. https://github.com/openapi-contrib/openapi-schema-to-json-schema/pull/6/files

**Comment by develohpanda** [comment]
Tagging @dimitropoulos for visibility

**Comment by dimitropoulos** [comment]
hey @philsturgeon: so @filfreire is actually going to be taking a look into this if I'm not mistaken.

we're hoping to improve the process so that PR authors can use a beta or alpha (or nightly!) very soon after the PR merges.

**Comment by philsturgeon** [comment]
@filfreire can you please manually release something if automation is tough? Or we can jump on a zoom call.

This is blocking us adding Guzzle support and I really don't want to fork this repo just to start getting releases again. The last release was September 2021. 

Please folks, let me help.

**Comment by filfreire** [comment]
This has since been done.
