### ISSUE TITLE
[Issue]HttpClient C#

### ISSUE THREAD

**Issue by spparida** [Kong/httpsnippet#190]
HttpClient(C#) not generating Content-Type for HttpClient (C#), but it's coming for all other languages supported. Pls check below screenshot for your reference. Can you pls respond on this, is it something a known issue , will be taking care in coming days? Pls let me know. Thanks you in advance!

![image](https://user-images.githubusercontent.com/21080088/96413338-20d88b00-1209-11eb-994f-20ea29dffab5.png)

![image](https://user-images.githubusercontent.com/21080088/96413356-27670280-1209-11eb-87a1-c58ac7c16239.png)

**Comment by erunion** [comment]
I believe this is fixed in https://github.com/Kong/httpsnippet/pull/188

**Comment by dimitropoulos** [comment]
as far as I can tell this is now fixed: https://github.com/Kong/httpsnippet/blob/d4bebe4ae27712021e94f8458064fe7c8599d493/src/targets/csharp/httpclient/fixtures/jsonObj-multiline.cs#L11
