### ISSUE TITLE
Implicitly coercing risk with Swift generated snippet.

### ISSUE THREAD

**Issue by irajtaghlidi** [Kong/httpsnippet#193]
The Swift snippet generator print `error` and `httpResponse` with **implicitly coercing** risk.

Xcode: 12.0.1

![snippet](https://user-images.githubusercontent.com/785830/97632545-b82cb200-1a43-11eb-8e95-e3acdd46e9d7.png)

**Comment by dimitropoulos** [comment]
fixed in https://github.com/Kong/httpsnippet/pull/195
