### ISSUE TITLE
Node.js / Fetch - `qs` isn't supported

### ISSUE THREAD

**Issue by p8952** [Kong/httpsnippet#201]
Code Generation for Node.js / Fetch using `node-fetch` generates code like this:

```
const fetch = require('node-fetch');

let url = '<REDACTED>';

let options = {
  method: 'GET',
  qs: {reference: '<REDACTED>'},
  headers: {
    'Content-Type': 'application/json'
  }
};

fetch(url, options)
  .then(res => res.json())
  .then(json => console.log(json))
  .catch(err => console.error('error:' + err));
```

However the `qs` option is not supported by `node-fetch`: https://github.com/node-fetch/node-fetch/issues/887

**Comment by jsohan** [comment]
params/query support would be a big help

**Comment by erunion** [comment]
Fix for this in https://github.com/Kong/httpsnippet/pull/213
