### ISSUE TITLE
Minify graphql before generating JSON

### ISSUE THREAD

**Issue by khrj** [Kong/httpsnippet#206]
Hi!
Is it possible to minify graphql before generating a snippet for it? At the moment,

```gql
query fetchRepos {
  user(login: "KhushrajRathod") {
    repositories(first: 100) {
      totalCount
      nodes {
        name
        stargazers(first: 100) {
          totalCount
          nodes {
            login
            avatarUrl
          }
        }
      }
    }
  }
}
```

will generate

```json
"{\"query\":\"query fetchRepos {\\n  user(login: \\\"KhushrajRathod\\\") {\\n    repositories(first: 100) {\\n      totalCount\\n      nodes {\\n        name\\n        stargazers(first: 100) {\\n          totalCount\\n          nodes {\\n            login\\n            avatarUrl\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\",\"operationName\":\"fetchRepos\"}"
```

rather than

```
"{\"query\":\"query fetchRepos{user(login:\\\"KhushrajRathod\\\"){repositories(first:100){totalCount nodes{name stargazers(first:100){totalCount nodes{login avatarUrl}}}}}}\",\"operationName\":\"fetchRepos\"}"```
```

I used https://codepen.io/dangodev/details/Baoqmoy to minify the above graphql

**Comment by erunion** [comment]
This library doesn't currently do any GraphQL generation.

**Comment by dimitropoulos** [comment]
ok, I have looked at this a few times and thought about it and I think I understand what the request is:

### What's being asked

Let's start with a concrete example, here is a HAR format request of the above (as generated by Insomnia):

```json
{
	"log": {
		"version": "1.2",
		"creator": {
			"name": "Insomnia REST Client",
			"version": "insomnia.desktop.app:v2022.5.0-beta.3"
		},
		"entries": [
			{
				"startedDateTime": "2022-07-27T20:06:06.551Z",
				"time": 0,
				"request": {
					"method": "POST",
					"url": "http://acme.com/graphql",
					"httpVersion": "HTTP/1.1",
					"cookies": [],
					"headers": [
						{
							"name": "Content-Type",
							"value": "application/json"
						}
					],
					"queryString": [],
					"postData": {
						"mimeType": "application/graphql",
						"text": "{\"query\":\"query fetchRepos {\\n  user(login: \\\"KhushrajRathod\\\") {\\n    repositories(first: 100) {\\n      totalCount\\n      nodes {\\n        name\\n        stargazers(first: 100) {\\n          totalCount\\n          nodes {\\n            login\\n            avatarUrl\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\",\"operationName\":\"fetchRepos\"}",
						"params": []
					},
					"headersSize": -1,
					"bodySize": -1,
					"settingEncodeUrl": true
				},
				"response": {
					"status": 0,
					"statusText": "",
					"httpVersion": "HTTP/1.1",
					"cookies": [],
					"headers": [],
					"content": {
						"size": 0,
						"mimeType": ""
					},
					"redirectURL": "",
					"headersSize": -1,
					"bodySize": -1
				},
				"cache": {},
				"timings": {
					"blocked": -1,
					"dns": -1,
					"connect": -1,
					"send": 0,
					"wait": 0,
					"receive": 0,
					"ssl": -1
				},
				"comment": "New Request"
			}
		]
	}
}
```

Take special note of the `postData` section:
```json
{
  "mimeType": "application/graphql",
  "text": "{\"query\":\"query fetchRepos {\\n  user(login: \\\"KhushrajRathod\\\") {\\n    repositories(first: 100) {\\n      totalCount\\n      nodes {\\n        name\\n        stargazers(first: 100) {\\n          totalCount\\n          nodes {\\n            login\\n            avatarUrl\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\",\"operationName\":\"fetchRepos\"}"
}
```

The `text` property contains a _string_ (not an object) that has an encoded JSON string contained within it.

If you parse that JSON inside `postData.text` you get another object with two keys, `operation` and `query`.  Here it is formatted:

```json
{
  "query": "query fetchRepos {\n  user(login: \"KhushrajRathod\") {\n    repositories(first: 100) {\n      totalCount\n      nodes {\n        name\n        stargazers(first: 100) {\n          totalCount\n          nodes {\n            login\n            avatarUrl\n          }\n        }\n      }\n    }\n  }\n}",
  "operationName": "fetchRepos"
}
```

Well now... there _again_ it's an encoded string, but this time it's not JSON. It's the GraphQL query syntax.

What @khrj is asking, per my understanding, is for _this_ string to be minified.

### If someone tries in the future

Today, this is a bit too specific for what HTTPSnippet does, but I would definitely welcome a PR.

If someone decides to reopen this issue in the future, here's some notes:
1. create a boolean option called `minifyGraphQL` on the cURL target
1. look for requests with a `mimeType` of `application/graphql`
1. from there you have to `JSON.parse` `postData.text`
1. from there you will get an object with a `query` key
1. contained in the value of the `query` element of the object you parsed above, you'll get a GraphQL query syntax
1. somehow, you'll need to minify that syntax cheaply.  we don't want to pull something like prettier into the HTTPSnippet shipped sourcecode.

### Consideration of potential blockers

and, most of all, that last step above is the one that motivates me to close this ticket for now.  unless someone can find a trivial way to do this, I can't see us merging something like this in without a large increase in bundle size, based on GraphQL minification tools I'm aware of.  with that said.. I'm super open minded, so if someone has a way to do this that's reliable and well tested and cheap (cheap in terms of bundle size), then I'd be glad to reopen and take a better look!
