### ISSUE TITLE
Server side build is failing due to 'window is not defined'

### ISSUE THREAD

**Issue by hirenoble** [Kong/httpsnippet#212]
I'm seeing an issue building a Gatsby site which uses this package to generate code sample.
  WebpackError: ReferenceError: window is not defined

This is because of this line of code 
```
var MultiPartForm = require('form-data')
```
any help would be appreciated!

**Comment by dimitropoulos** [comment]
we recently updated this npm, `form-data` from 3.0.0 to 4.0.0.  Please give it another try if you can.  There is a low likelihood that we can do anything about this 3rd party code, but it seems like https://github.com/form-data/form-data/issues/485#issuecomment-767494008 is an example of the same thing happening to someone else (completely with a solution.  If nothing else (and you can try this before upgrading) I would try that solution in https://github.com/form-data/form-data/issues/485#issuecomment-767494008 first.

Let us know if you can find reproduction steps and we can reopen.
