### ISSUE TITLE
curl multipart/form-data snippet includes unwanted boundary 

### ISSUE THREAD

**Issue by nateslo** [Kong/httpsnippet#226]
The snippet generated for a multipart form data request for curl includes a boundary in the headers. curl appends it own boundary header, resulting in two boundaries and the request fails.

Example snippet generated (with the addition of the verbose flag): 
```
curl --request POST \
  --url https://mockbin.org/echo \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --header 'accept: application/json' \
  --form 'filename=@nyancat32x32.png;type=image/png' \
  -v
 ``` 
 
 We can see that the request was sent with double boundaries, one from httpsnippet, and one added by curl:
 ```
  Content-Type: multipart/form-data; boundary=---011000010111000001101001; boundary=------------------------c18ea9ee9be9cb74
  ```
  As far as I can tell, httpsnippet always adds the `boundary=---011000010111000001101001'` to every multipart/form-data request. Any ideas of a way around this?

**Comment by reynolek** [comment]
@erunion Have you run into this? Per [this commit](https://github.com/Kong/httpsnippet/commit/86c52ba99e4ad36ecbd441d22f4ac525f7c9b39f) you made a change dealing with the boundary, not sure if related, or if we need to do something in the code to prevent curl from adding the custom boundary (or allowing curl to use our custom boundary?)

**Comment by erunion** [comment]
Oof, I haven't run into this. 😬 

We can definitely rework the cURL target to not add a boundary but I worry that we'll need to fully audit all targets to see if they need boundaries added or if they handle that themselves.

**Comment by reynolek** [comment]
As far as I can tell, cURL doesn't support custom boundaries. It probably does need a full on audit, and that sounds brutal...I think scoping it down to just cURL for now is reasonable while we figure out what to do about the others.

**Comment by erunion** [comment]
I'll see if I can get a PR for yall for disabling it on just the cURL target by this weekend. I'm so sorry @nateslo!

**Comment by reynolek** [comment]
@nateslo is going to look into it today as well. I think it will be a pretty easy fix, but im also pretty sure your change didnt cause this issue.

The way curl works is that it will accept a custom boundary if you are using raw data. But if you are using `--form` it always creates its own boundary, causing double boundaries if you also specify one.
