### ISSUE TITLE
[objc/native] Improvements

### ISSUE THREAD

**Issue by thibaultcha** [Kong/httpsnippet#28]
I want to implement a couple more things:

About literals (I like literals because they generate less cluttered code snippets and allow more flexibility to the people pasting them):
- [ ] Add a `literals` or `verbose` flag (`verbose` would be more consistent with other targets): If true, will generate literals from parameters/headers like currently, if false, will just use the objects computed by httpsnippet. It will be a nice options if people don't want too much verbose at the cost of flexibility for "pasters".
- [x] ~~Make body parameters literals (not sure about this one: very verbose)~~
- [x] ~~Make querystring parameters literals (not sure about this one either: very verbose)~~

About code style (JS):
- [x] Comment what's going on in the generation (`native.js`)
- [x] Improve the code climate rating (:cry:)

About improvements that could be made but are waiting on general guidelines:
- [ ] Parse the response body from `NSData`. Need to wait on response definition for now.
- [ ] Add an option for explanatory comments generation? Depends if other languages will do that too in the future. It could be a new guideline.

**Comment by thibaultcha** [comment]
About building querystrings, a huge downside would be the extra verbose:

``` objective-c
NSURLComponents *components = [[NSURLComponents alloc] init];
NSURLQueryItem *q1 = [NSURLQueryItem queryItemWithName:@"foo" value:@"bar"];
NSURLQueryItem *q2 = [NSURLQueryItem queryItemWithName:@"hello" value:@"world"];
components.queryItems = @[ q1, q2 ];

NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:components.URL
                                                       cachePolicy:NSURLRequestUseProtocolCachePolicy
                                                   timeoutInterval:10.0];
// execute request through NSURLSession
```

Not sure about this. The same way, multipart requests are already very verbose in order to build the body.

**Comment by darrenjennings** [comment]
@thibaultcha is this resolved?

**Comment by thibaultcha** [comment]
@darrenjennings No way I could remember, sorry. Better close it and move on.

**Comment by darrenjennings** [comment]
Sounds like a plan. Thanks!
