### ISSUE TITLE
[docs] Full example

### ISSUE THREAD

**Issue by thibaultcha** [Kong/httpsnippet#30]
I am not sure anybody currently landing on this project understands instantly what it does, as there is no clear example of a generated code snippet, and **4 sections** before any example. What do you all think about including a full example, with a smaller file?

---
### HTTP Snippet

HTTP requests code snippet generator for many programming languages. (Or httpsnippet generates code snippets to perform HTTP requests in many languages? Something maybe simpler.)

> ### Targets
> ### Installation
### Example

From this request description:

```
<small fixture> (query.json)
```

Run:

```
$ httpsnippet query.json -t node
```

To generate a Node.js code snippet performing the request:

```
var request = require('request');
// ...
```

(and then the module example)

**Comment by thibaultcha** [comment]
Still no clear example of what this project do. Bump before release...

**Comment by montanaflynn** [comment]
+1
