### ISSUE TITLE
Create test fixtures for urls using the https protocol 

### ISSUE THREAD

**Issue by montanaflynn** [Kong/httpsnippet#39]
Some languages require you to be explicit about which protocol you are using. For example in Ruby you must set the `use_ssl` flag.

**Comment by ahmadnassri** [comment]
easy copy from the `short.json` example

**Comment by montanaflynn** [comment]
https://github.com/Mashape/httpsnippet/commit/b436a5d9409c4c862000dc59c99d623e1bfb9be1
