### ISSUE TITLE
Add support for Python Requests

### ISSUE THREAD

**Issue by jpadilla** [Kong/httpsnippet#43]

**Comment by fletom** [comment]
Yeah, the requests library is the canonical way to do HTTP requests in Python. It should be the default "target" for httpsnippet's Python snippet.

**Comment by ahmadnassri** [comment]
:+1:

**Comment by montanaflynn** [comment]
Thanks for the suggestion! I did a quick search and it looks like it does not support custom HTTP methods, @ahmadnassri let's define a way to handle this as it's the same case in some other libraries. 

For reference: http://docs.python-requests.org/en/latest/

**Comment by fletom** [comment]
@montanaflynn 

```
In [1]: import requests

In [2]: requests.request('BLAH', 'http://google.com')
Out[2]: <Response [405]>
```

**Comment by montanaflynn** [comment]
Good looking out, I don't know why I didn't find that the first time around... here's the doc http://docs.python-requests.org/en/latest/api/#requests.request

**Comment by montanaflynn** [comment]
I got the basic implementation done, although there's a few niceties that were left out. 

https://github.com/Mashape/httpsnippet/pull/46

**Comment by ahmadnassri** [comment]
now that's requests is merged, closing this ticket, niceties, can be a separate issue if needed.
