### ISSUE TITLE
Docs: README examples are outdates/broken

### ISSUE THREAD

**Issue by thibaultcha** [Kong/httpsnippet#5]
The README says:

```
httpsnippet my-api-endpoint.json --langauge php --output ./snippets
```

But typo aside, `--language` doesn't work, it's `--target` or `-t` now. Also I heard @SGrondin mentioning than the `out/` option was not working?

**Comment by ahmadnassri** [comment]
fixed the outdated `--language` reference. `--output` however works fine ...
