### ISSUE TITLE
Escape necessary for postfields?

### ISSUE THREAD

**Issue by sudhamshk** [Kong/httpsnippet#64]
Hai @AhmadNassri

Is `escape` necessary for `CURLOPT_POSTFIELDS` in [httpsnippet/src/targets/php/curl.js](https://github.com/Mashape/httpsnippet/blob/master/src/targets/php/curl.js#L70)? 
Instead we can enclose data in single quotes(' ') because it is effecting the readability for the end-users

**Comment by ahmadnassri** [comment]
that is one of things I wanted to change all around, the usage of `JSON.stringify` forces this, but I have found `util.inspect` to do a better job, so i'll be switching to that soon.

**Comment by dimitropoulos** [comment]
this was fixed in https://github.com/Kong/httpsnippet/pull/291 by using `json_encode`
