### ISSUE TITLE
JavaScript - Angular ($http)

### ISSUE THREAD

**Issue by abhijitkane** [Kong/httpsnippet#69]
https://docs.angularjs.org/api/ng/service/$http

**Comment by ahmadnassri** [comment]
good idea, PRs are welcome :)

**Comment by darrenjennings** [comment]
With angular 1.x (AngularJS) being old and smelly, would this still be useful? Closing, but I like the idea of having more "frameworks" targets. Will be especially nice when we have targets as their own npm package. Surprised no one has filed a ticket for axios, but #90 makes the most sense if you wanted to be framework agnostic / terse / browser friendly
