### ISSUE TITLE
Use in the browser?

### ISSUE THREAD

**Issue by marbemac** [Kong/httpsnippet#70]
What sorts of Node dependencies are currently required, and how difficult would you estimate a browser compatible version would be?

**Comment by ahmadnassri** [comment]
should be fairly simple and straightforward with browserify ... if I remove all the `require-directory` dependencies ... (which I'm planning to do, but PRs are also welcome)

it gets complicated with the tests because of `require-directory`, but otherwise, no special dependencies ...

are you asking for stoplight.io?

**Comment by marbemac** [comment]
Yes indeed! Doing some investigating, and was curious. Is this something you were/are planning to do? We might have time to tackle this in the next couple of months. I just haven't had a chance to look through the code and was curious what you thought the scope of work involved might look like.

**Comment by ahmadnassri** [comment]
yep, I have a branch locally, to remove `require-directory` but wasn't a priority so far ... 

whoever, gets to it first maybe? :)

would love to chat more about stoplight.io, very interested in playing, also perhaps some room for collaboration with Mashape ... can take this convo offline / email.

**Comment by marbemac** [comment]
Not a huge priority for us either just yet - right now we're firmly in the desktop environment, with access to node. That said, I could see this easily becoming the defacto http code gen library with browser support. Would be awesome :).

Absolutely, would love to chat! Shoot me a note marc [at] stoplight.io when you have a moment.

**Comment by ahmadnassri** [comment]
okay, so I looked at my code and it wasn't that much more left, so I wrapped it up and released under [`v1.16.4`](https://github.com/Mashape/httpsnippet/releases/tag/v1.16.4) _(removing dependency on `require-directory`)_ 

this _should_ make it work with Browserify now, but I haven't tested it ... 99% certain everything will work though ... _(famous last words)_ :wink: 

will send you email to chat further

**Comment by marbemac** [comment]
:+1: awesome! Will play around with a browser version in the next month or so. Thanks a bunch.

Looking forward to chatting.

**Comment by mxr576** [comment]
@marbemac Did you managed to run httpsnippet in browser?

I'm getting this error continuously with browserify:

``` js


Error: Cannot find module '../../is-buffer/index.js' from '/private/tmp'
    at /private/tmp/node_modules/resolve/lib/async.js:55:21
    at load (/private/tmp/node_modules/resolve/lib/async.js:69:43)
    at onex (/private/tmp/node_modules/resolve/lib/async.js:92:31)
    at /private/tmp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)


```

**Comment by mxr576** [comment]
Okay, it seems webpack can do this without any problem.

**Comment by ahmadnassri** [comment]
@mxr576 if you do a `production` install, it would not need the filesystem dependency ... 

https://github.com/Mashape/httpsnippet/blob/master/package.json#L74

**Comment by mxr576** [comment]
I've found other issue with this library. FormData refers to [HTML5's FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and it cannot be overridden properly in browsers (or at least I wasn't able to do that). But as I can see this module isn't a hard dependency of this module so it could be removed, what do you think?
https://github.com/mxr576/httpsnippet/commit/a968e69f4d814e349dc3d3ddcdd216708d0ee43e
https://github.com/mxr576/httpsnippet/commit/f6b6d92afe651e7adf79a21cbf9e662f76974bd3

Should I create a Pull request from these commits?

Browserify is still not working properly on this library for me, but webpack works fine.

**Comment by ahmadnassri** [comment]
@mxr576 I left a comment there, using `FormData` will ONLY work in the browser, not sure that's a good approach.

**Comment by mxr576** [comment]
You're right of course, here is a new, more "cross-platform-ish" solution to this problem: https://github.com/mxr576/httpsnippet/commit/4542425e69a45145c43350cf48e0647045efedfd
