### ISSUE TITLE
Occasional Bluebird failures?

### ISSUE THREAD

**Issue by nikz** [Kong/httpsnippet#72]
Every so often snippet generation will fail with blank output. The following gets written to STDERR:

```
✖ code_sample_322968423736805296.json20150921-8796-1364q6w fail: Catch filter must inherit from Error or be a simple predicate function

    See http://goo.gl/o84o68
```

(Note that `code_sample_322968423736805296.json20150921-8796-1364q6w` is just the name of the Tempfile I'm using)

Input JSON looks something like:

``` json
{"method":"GET","url":"http://testurl.com/test","httpVersion":"HTTP/1.1","headers":[{"name":"accept","value":"application/json"},{"name":"ApiKey","value":"YOUR API KEY HERE"}],"cookies":[],"queryString":[],"postData":{},"headersSize":-1,"bodySize":-1}
```

But the error seems intermittent - if I re-run httpsnippet with the same JSON usually it works fine.

**Comment by ahmadnassri** [comment]
fixed in `v1.16.5`
