### ISSUE TITLE
Don't convert header names to lowercase

### ISSUE THREAD

**Issue by gfloyd** [Kong/httpsnippet#74]
This is a super minor issue of aesthetics, but since HTTP header names are case insensitive, it would be nice if the header names are preserved as provided in the HAR object. I just think it looks nicer in my documentation to have:

```
-H 'Authorization: Bearer <Your Token>'
```

Instead of:

```
-H 'authorization: Bearer <Your Token>'
```

**Comment by ahmadnassri** [comment]
I believe there was a reason they were lowered... primarily to avoid duplication, but I have to confirm first ...

**Comment by deepakpathania-zz** [comment]
+1

**Comment by darrenjennings** [comment]
As part of discussion in #83 we will move this forward by not lowercasing headers, not de-duping, and making the code _not_ depend on a lowercases `content-type` key. Stay tuned for a PR...!

**Comment by darrenjennings** [comment]
Added a branch with a failing test so we can address this once we get a successful test suite and have more confidence in refactors like this: https://github.com/Kong/httpsnippet/tree/fix/74-dont-lowercase-header-keys

**Comment by Blacksmoke16** [comment]
This should depend on the HTTP version being used. [HTTP/1.1](https://tools.ietf.org/html/rfc2616#section-4.2) says header names are case-insensitive while [HTTP/2](https://tools.ietf.org/html/rfc7540#section-8.1.2) requires them to be lowercase.

**Comment by RolphH** [comment]
@darrenjennings when do you expect this (part of  #83) to be fixed?
