### ISSUE TITLE
Windows - Powershell

### ISSUE THREAD

**Issue by elssar** [Kong/httpsnippet#75]
https://technet.microsoft.com/en-us/library/hh849901.aspx

**Comment by ahmadnassri** [comment]
@elssar happy to collaborate on this, let me know if you'd like to kickstart this in a PR.

**Comment by xdanmeyerx** [comment]
Hey @ahmadnassri - Just wondering about this one. Just found the project and was really excited to see a task for powershell. Let me know if you want to collaborate. Thanks!

**Comment by ahmadnassri** [comment]
@xdanmeyerx that would be great! no progress has been done so far, so if you want to take this on, its all yours.

**Comment by 123dev** [comment]
+1

**Comment by symeonb** [comment]
+1

**Comment by portaljacker** [comment]
+1

**Comment by sunmorgus** [comment]
+1

**Comment by mattj2332** [comment]
@ahmadnassri - I would like to take this on.  Happy for me to fork httpsnippet and submit a pull request when I am done?

**Comment by lukas-lansky** [comment]
@matthewjob Please, go for it. Too much coordination there about such a simple addition. :-)

**Comment by mikecg** [comment]
+1

**Comment by masonjohnson** [comment]
+1

**Comment by ronplasse** [comment]
+1

**Comment by n1njab0b** [comment]
+1

**Comment by SFarageNIS** [comment]
+1 - I like the PR associated with this issue.

**Comment by ShaneCal** [comment]
+1

**Comment by sbryden-mbo** [comment]
+1

**Comment by DDriggs00** [comment]
+1

**Comment by FallenGameR** [comment]
+1

**Comment by vpinheiro86** [comment]
+1

**Comment by kenmaglio** [comment]
Status Update? Build Still Fails...

**Comment by srufle** [comment]
+1

**Comment by kenmaglio** [comment]
See: https://github.com/Kong/httpsnippet/pull/127  - Merged!
