### ISSUE TITLE
Feature Request - Request POJO code generation 

### ISSUE THREAD

**Issue by ed-george** [Kong/httpsnippet#79]
I believe it would be highly beneficial for the library to add POJO creation within its Java section.

Many popular libraries in Java development (e.g. Retrofit, GSON) use POJOs in HTTP requests during serialization, so having httpsnippet generate these objects from a request would therefore be quite useful.

An example of what I'd expect this feature to do can be seen using this example 
## Request (in cURL format)

```
curl -X POST -H "Content-Type: application/json" -d '{
  "Email": "email@example.com",
  "Password": "password",
  "Settings": {
    "MySetting": true
  }
}' "http://example.com/login"
```
## Generated

```
public class LoginRequest {
    private String email;
    private String password;
    private Settings settings;

   public String getEmail(){ return email; }
   public void setEmail(String email){ 
      this.email = email;
   }
   // ... more getters and setters 
}

public class Settings {
    public boolean mySetting;
    public void getMySetting(){ return mySetting; }
    public boolean setMySetting(boolean mySetting){
        this.mySetting = mySetting;
    }
}
```

Is this considered in scope for the library and if so, could it be added potentially?

**Comment by ahmadnassri** [comment]
I'll have to read up more on POJO in Java to understand the scope before answering ...

however in the surface, the main goal here is to have "runnable" code at the end, so any object such generation would have to done within the full sample code

**Comment by ahmadnassri** [comment]
quick questions that come to mind: 
- how to figure out types for getters and setters?
- how to deal with complex objects (such as multipart requests)?
- how to deal with file uploads?

if no clear answer can be attained, it might prove to be more costly to the end user to include these object abstractions than just the plain examples provided here

**Comment by dimitropoulos** [comment]
I've thought about this one a decent amount and I think it's outside of the scope of what HTTPSnippet currently tackles, today.

Ultimately, many of the clients and targets have ways that they could dig deeper into language internals, but the feedback above is evidence to me that it's usually quite complicated to do so.  In other words, the deeper we dive with HTTPSnippet's outputs, the more edge-cases we hit.  Also, we have seen with other clients and targets that incompatibilities arise much faster as you more deeply link the output to the UX/DX of a particular language or library, which is generally bad for users.

If you disagree or what I said doesn't make sense, please feel free to comment with some solutions to the questions posed in the comments above and we can reopen and see what we can do!
