### ISSUE TITLE
form.pipe is not a function

### ISSUE THREAD

**Issue by Karthik-M-L** [Kong/httpsnippet#84]
I bundled the module using browserify and used in my application, code is not generated for the mimetype is multipart/form-data and params is filled.
Then i changed the version of form-data in package.json to "^0.2.0" then the error is resolved.

**Comment by ahmadnassri** [comment]
thanks! I'll do a version bump and run full tests to confirm then release an updated version :)

**Comment by lott-ai** [comment]
@ahmadnassri I am running into this issue as well. Was it ever resolve? I can show how to reproduce if needed.

**Comment by ahmadnassri** [comment]
i'm yet to release a new version. will get to that soon.

**Comment by darrenjennings** [comment]
Moving this, see #111

**Comment by geesmart** [comment]
but i get same problem
