### ISSUE TITLE
HTTP Method not capitalized

### ISSUE THREAD

**Issue by RolphH** [Kong/httpsnippet#85]
The HTTP Method is not capitalized which is not correct. According RFC 7231, the HTTP method should be in capitals. 
As the methods are in lower cases, it breaks using the snippets for example with curl:

`curl --request get --url  http://example.com`

This example will result in a 400 Bad Request in most cases. The correct call should be:

`curl --request GET --url  http://example.com`

Can you quickly fix this, or should I (when I have time) create a PR?

**Comment by RolphH** [comment]
I believe httpsnippet should fix this, I found out I used lowercase methods when calling httpsnippet.  Using uppercase it showed correctly.

**Comment by ahmadnassri** [comment]
RFC 7231 states:

```
The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names.
```

it might be a problem with your HTTP server or API provider, furthermore, if you want the method capitalized, then make them capitalized in the source HAR file.
