### ISSUE TITLE
They should be an explicit error when using an invalid target from command line

### ISSUE THREAD

**Issue by edi9999** [Kong/httpsnippet#87]
I use the command line.

If I write : 

`httpsnippet -t curl test.har`

I get : 

```
✓ test.har > curl [default] :
false
```

Since curl is not a valid target, I would expect the program to write an error message such as : `curl` is not a valid target, here is the list of valid targets : ...

**Comment by darrenjennings** [comment]
I like it. Would be a good first issue if anyone is able.
