### ISSUE TITLE
Javascript conversion crashes during multipart form data

### ISSUE THREAD

**Issue by Karthik-M-L** [Kong/httpsnippet#88]
Hi,

In javascript code generation template you are doing deletion of content type header in case of multi part form data. Code crashes saying "Cannot read property 'indexOf' of undefined" if javascript conversion is called twice and if same snippet is converted to other language content header will be missing. 
Ex: 
var snippet = new HTTPSnippet(data);
console.log(snippet.convert('javascript'));
console.log(snippet.convert('javascript'));

Regards,
Karthik M L

**Comment by ahmadnassri** [comment]
can you provide an example?

**Comment by Karthik-M-L** [comment]
Any post request with postdata having mimetype multipart formdata will do.
If you want HAR i can give you

**Comment by dimitropoulos** [comment]
There are no longer any `.indexOf` calls in any JavaScript target.  If someone can reproduce this today (post https://github.com/Kong/httpsnippet/pull/248) then please let me know and we'll take a look.
