### ISSUE TITLE
JavaScript - Fetch API

### ISSUE THREAD

**Issue by shamasis** [Kong/httpsnippet#90]
https://developer.mozilla.org/en/docs/Web/API/Fetch_API

**Comment by shamasis** [comment]
Just keeping this listed here as a target request. Maybe someone (or I) will send a PR.

**Comment by ralphdas** [comment]
This also came up a a handy to-have addition to this project in my view. So +1 if anyone could provide a PR for this

**Comment by maticrivo** [comment]
any progress on landing the PR #98 for this?

**Comment by ghost** [comment]
I'm interested too but this project seems abandoned...

no commit since Apr 15, 2017 :disappointed:

**Comment by darrenjennings** [comment]
httpsnippet is slowly rising from the ashes of it's abandonment. Stay tuned. #98 is looking pretty good so will review that shortly!
![](https://media.giphy.com/media/5G98t8QjqBLK8/giphy.gif)
